name: Deployment Pipeline

on: 
  push:
    branches:
    - master
    - ramitaAle
    
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
      - name: revisar archivos
        run: ls -l
      - name: revisar direccion
        run: pwd
        
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: /home/runner/work/challenge_copia/challenge_copia
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer
          
      - name: otra forma de checker html
        uses: rundocs/checkout@master
        
      - name: intento test disponibilidad
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:80
          responseCode: '200,500'
          timeout: 2000
          interval: 500
        
        
      
      

