name: Deployment Pipeline

on: 
  push:
    branches:
    - master
    - ramitaAle
    
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
          
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer
